# Common configurable options

# mutating webhooks for automatic sidecar injection
sidecarInjectEnabled: false

# In order to enable auto-inject webhook you need to set this value:
#   kubectl get configmap -n kube-system extension-apiserver-authentication -o=jsonpath='{.data.client-ca-file}' | base64 | tr -d '\n'
#sidecarInjectCA: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRFM01EUXhPREl4TVRZMU9Gb1hEVEkzTURReE5qSXhNVFkxT0Zvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTnU3CkN4M09MRkVrbjlTZVBwQ1l0ZC9uWEMrNFlDWHRUc1YvZzJ0UVRWUU1UTjhpVkowYnVLQVViK0Z5c0QwSVR2TmYKeWJsaXU1b2F2R2gwSCtJKzI4TGd5U0NiaVNQbmkzWlozQTUrTzF2cFhJMzRmNklGNndscTZaL2F0U0NpV1JidAo1VnJTMlNVUHgrMVlvdDY5cGQyOEhkVWtXcUU2Tmc0aTZIbHpVQTNyMndNZXlhaUtPNldocmt5ZzlZcG9wQXZhCjV4MXpuTVBsa2MwY1RnaHVadklGNVJ1ZjFyMlVrTkFXc1k5cFpDVCtZTnZSQWd5aU1vZ1ZwOVppWE1LZ2JpWW0KOXJuR3czZTIzOWtxcXBuNXdaTzdscjZYcmQ1czBnK1hrZWxoT2RIbWxRVnp4eDBvRGVWZ1I0VFk5b3hYS3FCVgp2UktqbzZzLy9rNHFYZ1ExQXdrQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFDRWZzbTFlMkZkdFloL1ViRkN4d0R3RXprUENwbzZIWUsyck4zZno0Ym1XYUlJcDRxOApqTTVBWElDYmxDK1pqby9NZHhOWXlTbnBRU3lGeUdFTjBRdG8rUWVpYmVNazNEb215NnBKRXlRRTZpOUZhTFFJCloxOGs1VjdmakdOU0VHY290MUF0QmhaR0FROWFaZ1VqRndCaTlKTGJob25HN3pnTTNwclFuWURMbEZWVUtzcjEKcmg4QzA3a0hpMUMvcnJmRUlrTWxYWDFKWXk2aE4wQ0pmRzVoNWM4a0poY1B1K3BmazhZeTZiNXRpTjk2NEFkegprdmQyRlZpZWtOa3d1TGN5MVVTanBISzVrWVpyVk9OSThtTjUvbXIxeEZzVTdpYVJ5YVQ0TWhDTVZ2M0YvV0ljCjh3WUZxc3NHUVBJZ2IwMTI2SmRGeW9zSThyUHVHenFwVWlsdAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==

# if enabled, istio will use mtls by default for service to service, with a blacklist of
# services and service annotation to disable.
# if disabled, istio will not use mtls by default, but will honor annotations in the service.
defaultProxyMtls: false

# Istio tag. The version in git defaults to nightly, releases will replace this.
#istioTag: nightly
istioTag: 0.5.0

# Values need to be sett to enable stackdriver integration
#stackdriverProjectId: my_project_id
#stackdriverCredentials: credentials.json


# TODO: template for list of excluded services

# Set the following variable to true to disable policy checks by the Mixer.
# Note that metrics will still be reported to the Mixer.
disablePolicyChecks: false

# Control request tracing
enableTracing: true

# Along with discoveryRefreshDelay, this setting determines how
# frequently should Envoy fetch and update its internal configuration
# from Istio Pilot. Lower refresh delay results in higher CPU
# utilization and potential performance loss in exchange for faster
# convergence. Tweak this value according to your setup.
rdsRefreshDelay: 1s

# Enable mtls for communication with pilot/mixer
enableControlPlaneMtls: false

# =============== Testing or special cases only ============

# If running in minikube, uncomment this or run with --set ingressNodePort=30001
# ingressNodePort: 30080

# Image to use for the sidecar. Can be replaced with proxy_debug for debug version,
# or a custom build.
proxyImage: proxy

# Configure envoy to send statsd UDP updates to mixer.
enableEnvoyStatsd: true

# Namespace where istio control plane is installed.
istioNamespace: istio-system

# Hub used to fetch istio images
istioHub: docker.io/istio

# create RBAC resources
rbacEnabled: true

global:
  # Not recommended for user to configure this. Hyperkube image to use when creating custom resources
  hyperkube:
    repository: {HYPERKUBE_HUB}
    tag: {HYPERKUBE_TAG}

imagePullPolicy: IfNotPresent

resources: {}
nodeSelector: {}

# istio ingress configuration
ingress:
  enabled: true
  # By default istio ingress uses LoadBalancer type of service
  # to use NodePort, it needs to be enabled and desired port specified
  nodePort:
    enabled: false
    port: 32000

#
# sidecar-injector configuration
#
sidecarInjector:
  enabled: true
  serviceAccountName: default # used only if RBAC is not enabled
  replicaCount: 1
  imagePullPolicy: IfNotPresent
  resources: {}
  nodeSelector: {}

#
# mixer configuration
#
mixer:
  enabled: true
  serviceAccountName: default # # used only if RBAC is not enabled
  replicaCount: 1
  imagePullPolicy: IfNotPresent
  resources: {}
  nodeSelector: {}

  prometheusStatsdExporter:
    repository: prom/statsd-exporter
    tag: latest
    imagePullPolicy: IfNotPresent
    resources: {}

#
# pilot configuration
#
pilot:
  enabled: true
  serviceAccountName: default # # used only if RBAC is not enabled
  replicaCount: 1
  imagePullPolicy: IfNotPresent
  resources: {}
  nodeSelector: {}

#
# security configuration
#
security:
  # Itio CA started
  enabled: true
  # mutual TLS authentication
  mtls: false
  serviceAccountName: default # # used only if RBAC is not enabled
  replicaCount: 1
  imagePullPolicy: IfNotPresent
  resources: {}
  nodeSelector: {}
